# Generated by Django 2.2 on 2020-10-04 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=40, verbose_name='Debtor phone number')),
                ('full_name', models.CharField(max_length=80, verbose_name='Debtor full name')),
                ('email', models.EmailField(max_length=60, verbose_name='Debtor email')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ammount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='Debtor ammount')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Date loan ammount')),
                ('expected_payment_date', models.DateTimeField(verbose_name='Date loan date payment')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment status')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor')),
            ],
        ),
    ]
