# Generated by Django 2.2 on 2020-09-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='email',
            field=models.EmailField(default=None, max_length=60, verbose_name='Debtor email'),
        ),
    ]
