# Generated by Django 2.2 on 2020-09-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_auto_20200920_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Debtor email'),
        ),
    ]
