# Generated by Django 2.2 on 2020-09-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0003_auto_20200920_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='Debtor ammount')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Date loan ammount')),
                ('loan_payment_date', models.DateTimeField(verbose_name='Date loan date payment')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor')),
            ],
        ),
    ]
